config/routes.rb
Rails.application.routes.draw do
  
  resources :wishlists
  resources :products

  devise_for :users

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :users, through: :wishlists
	has_many :wishlists

	# validates :sku, numericality: true,
	# 	length: {
	# 		minimum: 7,
	# 		maximum: 7
	# 	},
	# 	uniqueness: true

	def self.calc_rate(currentPrice, regPrice)
		if currentPrice <  regPrice
			downRate = ((1 - (currentPrice/regPrice)) * 100).round
		elsif currentPrice > regPrice 
			upRate = (((currentPrice/regPrice) - 1) * 100).round
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :products, through: :wishlist
  has_many :wishlists
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
	belongs_to :product
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end

  def after_sign_in_path_for(resource)
    request.env['omniauth.origin'] || products_path(resource) || root_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @products = Product.all
    @wishlists = Wishlist.where(user_id: current_user.id)
    # respond_to do |format|
    #   format.html
    #   format.json {render json: @products}
    # end
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.rate_of_change = Product.calc_rate(@product.price, @product.regPrice)
    if @product.save
      @wishlist = Wishlist.new(user_id: current_user.id, product_id: @product.id)
      @wishlist.save
      respond_to do |format|
      format.html {redirect_to product_path}
      format.json {render json: @products}
      end
    end
  end

  def update
    @product.update(product_params)
    if @product.update
      respond_to do |format|
      format.html
      format.json {render json: @products}
      end
    end
  end

  def destroy
    @product.destroy
    if @product.destroy
      respond_to do |format|
      format.html {redirect_to products_path}
      format.json {render json: @products}
      end
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :asin, :price, :rate_of_change, :description, :regPrice, :url, :img_url)
    end

    def wishlist_params
      params.require(:wishlist).permit(:user_id, :product_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def index
		if current_user != nil
			redirect_to products_path
		end
	end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  before_action :set_wishlist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @wishlists = Wishlist.all
    @products = Product.all
  end

  def show
    
  end

  def new
    @wishlist = Wishlist.new
    respond_to do |format|
      format.html
      format.json {render json: @wishlist}
    end
  end

  def edit
  end

  def create
    @wishlist = Wishlist.new(user_id: current_user.id, product_id: @product.id)
    @wishlist.save
    respond_to do |format|
      format.html
      format.json {render json: @wishlist}
    end
  end

  def update
    @wishlist.update(wishlist_params)
  end

  def destroy
    @wishlist.destroy
      if @wishlist.destroy
        respond_to do |format|
        format.html {redirect_to products_path}
        format.json {render json: @products}
      end
    end
  end

  private
    def set_wishlist
      @wishlist = Wishlist.find(params[:id])
    end

    def wishlist_params
      params.require(:wishlist).permit(:user_id, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class="signin">
      <% if user_signed_in? %>
        Welcome! <%= current_user.email %> | Not you? <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "sign in", new_user_session_path %>
      <% end %>
    </div> 
      
    </div>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/products/_form.html.erb
<form id="search">
  <input type="search" id="product" placeholder="Enter Product URL">
  <input type="submit" value="Search">
</form>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
   
    <%= render 'form' %>
    
    
    <div id="product-list">
      <h1>Product Wishlist</h1>
      <ul>
        <% @wishlists.each do |item| %>
        <li>
          <a class="expand">
          <div class="right-arrow">+</div>
          <div class="img_url"><img src="<%= item.product.img_url %>"></div>
          <div class="large-5 columns">
            <h3><%= item.product.name %></h3>
          </div>
          <div class="price-container">
          <div class="current-price columns">
            <span>$<%= item.product.price %></span>
          </div>
          <div class="reg-price columns">
            <span>%<%= item.product.rate_of_change %></span>
          </div>
          </div>
          </a>
          
          <div class="detail">
            <div class="description"><span><%= item.product.description %></span></div><br/>
            <div id="delete-item">
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
          
           <% end %>
          </li>
          
      </ul>
     </div>
    </div>

<br>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Asin:</strong>
  <%= @product.asin %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Rate of change:</strong>
  <%= @product.rate_of_change %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/welcome/index.html.erb
<div id="letter-container" class="letter-container">
			<div id="banner">
				<h2>
					<a href="#">Contango</a>
				</h2>
			</div>

app/views/wishlists/_form.html.erb
<%= form_for(@wishlist) do |f| %>
  <% if @wishlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wishlist.errors.count, "error") %> prohibited this wishlist from being saved:</h2>

      <ul>
      <% @wishlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wishlists/edit.html.erb
<h1>Editing wishlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<h1>Listing wishlists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlists.each do |wishlist| %>
      <tr>
        <td><%= link_to 'Show', wishlist %></td>
        <td><%= link_to 'Edit', edit_wishlist_path(wishlist) %></td>
        <td><%= link_to 'Destroy', wishlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist', new_wishlist_path %>

app/views/wishlists/new.html.erb
<h1>New wishlist</h1>

<%= render 'form' %>

<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>